pre_src_prepare() {
    if ! type epatch_user > /dev/null 2>&1; then
        local names="epatch_user epatch evar_push evar_push_set evar_pop estack_push estack_pop"
        source <(awk "/^# @FUNCTION: / { p = 0 } /^# @FUNCTION: (${names// /|})\$/ { p = 1; } p { print  }" /usr/portage/eclass/eutils.eclass)
    fi

    epatch_user

    for name in $names; do
        unset $name
    done

    #unset DEBUG for packages known to break.
    if test "$PN" = "gsm" -o "$PN" = "libunique"; then
      unset DEBUG
    fi
    #TODO: make a more general thing here, like package.env is, but this one is for overriding even existing env. vars
    #set >/tmp/set.txt
}

