#!/bin/bash

#1st time ssh

to="$1"

if test -z "$to"; then
  echo -n "unspecified to='$to' "
  to="${0//*3scpfrom_/}"
  echo "using '$to'"
#  exit 1
else
  shift
fi

export to

`dirname -- "$0"`/0scpfrom "$@"

