#!/bin/bash

#this shows the diff for modified files 
#and also shows the deleted files as lines beginning with: Only in rsync-backed/

thedir='rsync-backed'  #TODO: make these vars a common file sourced in each script!

sudo diff -rup "$thedir" gentoo |grep -E -v '^Only in gentoo' | colordiff | less
#^ sudo is needed because gentoo/root for example is inaccessible to normal user!


sudo diff -rup "$thedir" gentoo |grep --color=tty "Only in $thedir"

sudo diff -rup "$thedir" gentoo |grep --color=tty "^Binary files "

