#!/bin/bash

fromlocalpath="$1"
toremotepath="$2"

if test -z "$fromlocalpath" -o -z "$toremotepath"; then
  echo "empty args?"
  exit 2
fi

set -x
time scp -i ~/privaterepos/ticu/dns/lekeyofhss/privk -4vp -r -P 46802 "$fromlocalpath" root@latelier:"$toremotepath"
set +x


