#!/bin/bash

sudo smartctl --all -- /dev/sda >smartctl--all.log

ssdwrittenlogfile='ssdwritten.log'
tmpfile="${ssdwrittenlogfile}.tmp"
ssdwritten > "$tmpfile"
if test -e "$ssdwrittenlogfile"; then
  difference="`cat "$tmpfile" "$ssdwrittenlogfile" | awk '{print $3}' |sed ':a;N;$!ba;s/\n/-/'|bc`"
  echo "$difference" > bytes_written_since_last_commit.log
fi
mv -- "$tmpfile" "$ssdwrittenlogfile"

