#!/bin/bash

#this shows the diff for modified files 
#and also shows the deleted files as lines beginning with: Only in rsync-backed/

thedir='rsync-backed'  #TODO: make these vars a common file sourced in each script!

sudo diff --exclude="/${thedir}" -rup "$thedir" / |grep -E -v '^Only in /' | colordiff | less
#^ sudo is needed because gentoo/root for example is inaccessible to normal user!


sudo diff --exclude="/${thedir}" -rup "$thedir" / |grep "Only in $thedir"

