#!/bin/bash

#this shows the diff for modified files 
#and also shows the deleted files as lines beginning with: Only in rsync-backed/

thedir='rsync-backed'  #TODO: make these vars a common file sourced in each script!

#hmm, we don't have sudo and diff when booting from admincd, BUT diff is there inside chroot!
#also colordiff we don't have.

sudo2() {
 cmd="$@"
 if ! sudo "$@"; then
	 ${cmd}
 fi
}

colordiff2() {
	if ! colordiff; then
		tee
	fi
}

sudo2 diff --exclude="${thedir}" -rup "$thedir" ./ |grep -E -v '^Only in ./' | colordiff2 | less -R
#^ sudo is needed because gentoo/root for example is inaccessible to normal user!


sudo2 diff --exclude="${thedir}" -rup "$thedir" ./ |grep "Only in $thedir"

