#!/bin/bash

#overridden by the iptables rules in /etc/iptables/iptables.rules
exit 1

#src: https://ubuntuforums.org/showthread.php?t=1188099
iptables -C OUTPUT -m owner --gid-owner no-internet -j DROP || iptables -I OUTPUT -m owner --gid-owner no-internet -j DROP

