#!/bin/bash

#set -e
pushd /
(
for i in /patches/webrsync/*.patch ; do 
  #patch -Np1 -i /home/zazdxscf/patches/webrsync/notify_when_patches_folder_inaccessible_by_portage.patch
  patch -Np1 -i "$i"
  ec="$?"
  if test "$ec" -ne "0"; then
    echo "FAILED!" | grep --color=tty "FAIL"
  fi
done
)
popd
:

