#!/bin/bash

fil='/tmp/kernel_versions.diff'

#v1=linux-4.1.6-hardened-r1/
#v2=linux-4.1.6-hardened-r2/
#v1=linux-4.1.7-hardened/
#v2=linux-4.1.7-hardened-r1/
what=linux-4.2.3-hardened
v1=${what}-r1/
v2=${what}-r2/

diff -rup --exclude=*.mod.c --exclude=*.map --exclude=*.S --exclude=config_data.h  -- "$v1" "$v2" |grep -v "Binary " |grep -v "Only in " > "$fil"
cat "$fil" |colordiff|less

